<!--    
    SCRIPTING stuff
-->
<script type="text/javascript">
    var articleData = {
        "r": "<?php echo $this->r; ?>",
        "rDescription": <?php echo json_encode ($this->rDescription); ?>,
        "articleUrl": "<?php echo $this->articleUrl; ?>",
        "imagesPath": "<?php echo $this->articleImagesUrl; ?>"
    };
</script>

<!-- Generated Javascript files -->

<!-- Libraries -->

<!-- CSS files -->
<link rel="stylesheet" href="<?php echo $this->articleCssUrl; ?>articleontologyModule.css" />

<!--
    HTML area
-->

<div style=""> 
    
    <!-- Model has already an associated article -->
    <?php if (true == $this->moduleHasArticle) { ?>
    
        <span style="font-size:12px; color:#737373;">
            You can change the associated article by clicking to
        </span>
        <img src="<?php echo $this->articleImagesUrl; ?>pencil.png" align="absmiddle"/>
        <a href="<?php echo $this->articleUrl .'edit/?r='. $this->selectedModelIri; ?>">
            Edit</a>  
    
    <!-- No article is associated with model -->
    <?php } else { ?>
        
        <span style="font-size:12px; color:#737373;">
            You have the possibility to add a new article to the selected model.
        </span>
                
        <!-- Icon -->
        <img src="<?php echo $this->articleImagesUrl; ?>add.png" align="absmiddle"/>
        
        <!-- Link -->
        <a href="<?php echo $this->articleUrl .'edit/'; ?>">
            Add</a>
    
    <?php } ?>
    
    <br/>
    <br/>
    <span style="font-size:12px; color:#737373;">
        Here you will see a list of all articles in this model by clicking to &nbsp;
    </span>
    <img src="<?php echo $this->articleImagesUrl; ?>icon-list.png" align="absmiddle"/>
    <a href="<?php echo $this->articleUrl; ?>">
        List articles</a>
    
</div>

