<div id="article-ArticleOntologyModule-Content"> 
        
    <span id="article-ArticleOntologyModule-NotificationText">
        You have the possibility to add a new article to the selected model.
    </span>
            
    <!-- Icon -->
    <img src="<?php echo $this->articleImagesUrl; ?>add.png"/>
    
    <!-- Link -->
    <a href="<?php echo $this->articleUrl .'edit/?createnew=true'; ?>">
        Add <?php echo $this->rClassLabel; ?>
    </a>
    
    <br/>
    <br/>
    
    <span style="font-size:12px; color:#737373;">
        Here you will see a list of all articles in this model by clicking to &nbsp;
    </span>
    
    <img src="<?php echo $this->articleImagesUrl; ?>icon-list.png" align="absmiddle"/>
    
    <a href="<?php echo $this->articleUrl; ?>">
        List <?php echo $this->rClassLabel; ?>
    </a>
    
</div>

