<script type="text/javascript">
    var articleData = {
        "r": "<?php echo $this->r; ?>",
        "rDescription": <?php echo json_encode ($this->rDescription); ?>,
        "articleUrl": "<?php echo $this->articleUrl; ?>",
        "imagesPath": "<?php echo $this->articleImagesUrl; ?>",
        "BBEditor": {
            "textareaId": "article-Edit-EditorContent", 
            "toolbarId":  "article-Edit-Toolbar",
            
            // List of element which will be shown in the toolbar in the given order
            "toolbarEntries": [
                { "image": "boldB.png", "name": "boldBtn", "title": "Bold", "type": "bold" },
                { "image": "italicI.png", "name": "italicBtn", "title": "Italic", "type": "italic" },
                { "image": "codeLine.png", "name": "codeLineBtn", "title": "Code line", "type": "codeLine" },
                { "image": "codeBlock.png", "name": "codeBlockBtn", "title": "Code block", "type": "codeBlock" },
                { "image": "list.png", "name": "listBtn", "title": "Unordered list", "type": "list" },
                { "image": "quote.png", "name": "quoteBtn", "title": "Quoting text", "type": "quote" }
            ]
        }
    };
</script>

<div id="article-Edit-ContentArea">  
  
    <div style="width: 80%">
        <span style="font-weight:bold;"><?php echo $this->labelLabel; ?></span>
        <!-- label input field -->
        <input type="text" id="article-Edit-LabelField" name="rlabel" value="<?php echo $this->rLabel; ?>"/>
    </div>
    
    <br/>
        
    <div style="width:80%;">
        <!-- Editor with toolbar -->
        <div id="article-Edit-TabEditor">
            <div id="article-Edit-Toolbar"></div>
            <div style="margin-top: 8px;"></div>
            <textarea id="article-Edit-EditorContent"></textarea>
        </div>

        <!-- Preview -->
        <div id="article-Edit-TabPreview"></div>
    </div>
    
</div>
