<script type="text/javascript">
    var articleData = {
        "r": "<?php echo $this->r; ?>",
        "rLabel": <?php echo json_encode ($this->rLabel); ?>,
        "rDescription": <?php echo json_encode ($this->rDescription); ?>,
        "articleUrl": "<?php echo $this->articleUrl; ?>",
        "imagesPath": "<?php echo $this->articleImagesUrl; ?>",
        "insertUpdateInformation": {
            "newResourceTypeUri" :      "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            "newResourceClassUri" :     "<?php echo $this->newResourceClassUri; ?>",
            "namedGraphUri" :           "<?php echo $this->namedGraphUri; ?>",
            "serviceUpdateURL" :        "<?php echo $this->owUrl.'service/update/'; ?>",
            "contentPropertyUri" :      "<?php echo $this->contentPropertyUri; ?>",
            "contentDatatype" :         "<?php echo $this->contentDatatype; ?>",
            "resourceLabelUri":         "<?php echo $this->resourceLabelUri; ?>",
            "resourceLabelDataType":    "<?php echo $this->resourceLabelDataType; ?>",
            "resourceLabelLang":        "<?php echo $this->resourceLabelLang; ?>"
        },
        "BBEditor": {
            "textareaId": "article-Edit-EditorContent", 
            "toolbarId":  "article-Edit-Toolbar",
            
            // List of element which will be shown in the toolbar in the given order
            "toolbarEntries": [
                { "image": "boldB.png", "name": "boldBtn", "title": "Bold", "type": "bold" },
                { "image": "italicI.png", "name": "italicBtn", "title": "Italic", "type": "italic" },
                { "image": "codeLine.png", "name": "codeLineBtn", "title": "Code line", "type": "codeLine" },
                { "image": "codeBlock.png", "name": "codeBlockBtn", "title": "Code block", "type": "codeBlock" },
                { "image": "list.png", "name": "listBtn", "title": "Unordered list", "type": "list" },
                { "image": "quote.png", "name": "quoteBtn", "title": "Quoting text", "type": "quote" }
            ]
        }
    };
</script>

<div id="article-Edit-ContentArea">  

    <div style="height:40px;">
        <!-- Notification to show if saving was successfully -->
        <p class="messagebox success" id="article-Edit-SavingSuccessNotif" style="display: none;">
            Article saved</p>
        
        <!-- Notification to show if saving was not possible -->
        <p class="messagebox error" id="article-Edit-SavingNotPossibleNotif" style="display: none;">
            Saving not possible: </p>
    </div>
  
    <div style="width: 80%">
        <span style="font-weight:bold;"><?php echo $this->labelLabel; ?></span>
        <!-- label input field -->
        <input type="text" id="article-Edit-LabelField" name="rlabel" value="<?php echo $this->rLabel; ?>"/>
    </div>
    
    <br/>
        
    <div style="width:80%;">
        <!-- Editor with toolbar -->
        <div id="article-Edit-TabEditor">
            <div id="article-Edit-Toolbar"></div>
            <div style="margin-top: 8px;"></div>
            <textarea id="article-Edit-EditorContent"></textarea>
        </div>

        <!-- Preview -->
        <div id="article-Edit-TabPreview"></div>
    </div>
    
</div>
