<!--    
    SCRIPTING stuff
-->
<script type="text/javascript">
    var articleData = {
        "r": "<?php echo $this->r; ?>",
        "rDescription": <?php echo json_encode ($this->rDescription); ?>,
        "articleUrl": "<?php echo $this->articleUrl; ?>",
        "imagesPath": "<?php echo $this->articleImagesUrl; ?>",
        "BBEditor": {
            "textareaId": "article-EditorContent", 
            "toolbarId":  "article-Toolbar",
            
            // List of element which will be shown in the toolbar in the given order
            "toolbarEntries": [
                { "image": "boldB.png", "name": "boldBtn", "title": "Bold", "type": "bold" },
                { "image": "italicI.png", "name": "italicBtn", "title": "Italic", "type": "italic" },
                { "image": "codeLine.png", "name": "codeLineBtn", "title": "Code line", "type": "codeLine" },
                { "image": "codeBlock.png", "name": "codeBlockBtn", "title": "Code block", "type": "codeBlock" },
                { "image": "list.png", "name": "listBtn", "title": "Unordered list", "type": "list" },
                { "image": "quote.png", "name": "quoteBtn", "title": "Quoting text", "type": "quote" }
            ]
        }
    };
</script>

<!-- Generated Javascript files -->
<script type="text/javascript" src="<?php echo $this->articleJavascriptUrl; ?>BBEditor.js"></script>
<script type="text/javascript" src="<?php echo $this->articleJavascriptUrl; ?>EditAction.js"></script>

<!-- Libraries -->
<script type="text/javascript" src="<?php echo $this->articleJavascriptLibrariesUrl; ?>showdown.js"></script>

<!-- CSS files -->
<link rel="stylesheet" href="<?php echo $this->articleCssUrl; ?>editAction.css" />

<div id="article-Edit-ContentArea">  
  
    <div style="width: 80%">
        <span style="font-weight:bold;"><?php echo $this->labelLabel; ?></span>
        <!-- label input field -->
        <input type="text" id="article-label-field" name="rlabel" value="<?php echo $this->rLabel; ?>"/>
    </div>
    
    <br/>
        
    <div style="clear:both;">
        <!-- Editor with toolbar -->
        <div id="article-Edit-TabEditor">
            <div id="article-Toolbar"></div>
            <div style="margin-top: 8px;"></div>
            <textarea id="article-EditorContent"></textarea>
        </div>

        <!-- Preview -->
        <div id="article-Edit-TabPreview"></div>
    </div>

    <div style="margin-top: 10px;"></div>
    
    <div style="clear:both;">
        <input type="button" class="submit minibutton" value="Save changes" id="article-SaveBtn">
        <span id="article-Edit-SavingSuccessNotif">Saving successfully!</span>
    </div>
    
    <br/>
    <br/>
    
</div>
